# Generated by Django 4.2 on 2024-12-25 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("satisfaction", "0002_visite"),
    ]

    operations = [
        migrations.AddField(
            model_name="avis",
            name="visite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avis",
                to="satisfaction.visite",
            ),
        ),
    ]
