# Generated by Django 5.1.4 on 2025-01-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfaction', '0003_avis_visite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='designation',
            field=models.CharField(max_length=50),
        ),
    ]
