# Generated by Django 5.1.4 on 2025-01-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satisfaction', '0004_alter_service_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='service',
        ),
    ]
