# Generated by Django 5.1.4 on 2025-01-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satisfaction', '0005_remove_avis_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
