# Generated by Django 5.1.4 on 2025-01-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfaction', '0007_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='visite',
            name='ref_pat',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visite',
            name='service',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visite',
            name='specialite',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
